// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA8WFW26byZXXIe0kb5B2Bn3GAMZ4kphY',
    appId: '1:619796484881:web:7373e1ee2ce352b42ab2b0',
    messagingSenderId: '619796484881',
    projectId: 'invest-3639a',
    authDomain: 'invest-3639a.firebaseapp.com',
    storageBucket: 'invest-3639a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS0qPOcVHIQxKkXVCnQpez49Din44aGe4',
    appId: '1:619796484881:android:e8ce763da25967312ab2b0',
    messagingSenderId: '619796484881',
    projectId: 'invest-3639a',
    storageBucket: 'invest-3639a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh6luUS_JhWYClkYzYSD7nLE4P10P_9HQ',
    appId: '1:619796484881:ios:47454cf72957d8622ab2b0',
    messagingSenderId: '619796484881',
    projectId: 'invest-3639a',
    storageBucket: 'invest-3639a.appspot.com',
    iosBundleId: 'com.example.investApp',
  );
}
